baseURL = 'https://peatiscoding.github.io/'
languageCode = 'en-us'
title = 'peatiscoding.github.io'
theme = "hugo-winston"

[params]
  google_analytics_id = "G-9PN5X6JRGV"
  twitter_handle = "@peatiscoding"

  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false

  addFrame = true
  addDot = true

  highlightColor = '#7b16ff'
